#        - image: turkiznazaba/appointments:2023-12-01-09-21-36 #to be changed

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
        - image: turkiznazaba/appointments:2024-01-04-12-15-45 #to be changed
          name: appointments
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
#              value: jdbc:postgresql://ella.db.elephantsql.com:5432/hdalyqbh
              value: jdbc:postgresql://dumbo.db.elephantsql.com:5432/frswtwtv
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: frswtwtv
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbpasswordappointments
                  key: dbpasswordappointments
          ports:
            - containerPort: 8080
              name: server

---

apiVersion: v1
kind: Service
metadata:
  name: appointments
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: appointments
